all:
	gcc -Wall -g 4.2.c program_handler2.c mtx_sema.c parser.c var_storage.c labels.c -o 4.2 -lpthread -lm
d:
	gcc -Wall -g 4.2.c program_handler2.c mtx_sema.c parser.c var_storage.c labels.c -o 4.2 -lpthread -lm -Ddebug

